server:
  port: 8080

spring:
  application:
    name: Ecommerce Application
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true